### ISSUE TITLE
Update HelloScalanStaged  example in readme

### ISSUE THREAD

**Issue by aslesarenko** [scalan/scalan-ce#15]
See [Discussion thread](https://groups.google.com/forum/#!msg/scalan/whKqz4yUKGA/SUbmpA9Wm6YJ)

**Comment by alexeyr** [comment]
Updated and added https://github.com/scalan/scalan-ce/blob/master/lms-backend/src/test/scala/HelloScalan.scala to make sure it doesn't go stale again.
