### ISSUE TITLE
New meta doesn't accept Arr[T] as valid return type

### ISSUE THREAD

**Issue by knizhnik** [scalan/scalan-ce#33]
17:44:44.963 [run-main-2] WARN  scalan.meta.EntityManagement - Cannot generate matcher for method `BaseTable.toArray`: Method's return type Arr[R] is not a Rep
17:44:44.970 [run-main-2] WARN  scalan.meta.EntityManagement - Cannot generate matcher for method `UniqueIndex.toArray`: Method's return type Arr[R] is not a Rep
17:44:44.972 [run-main-2] WARN  scalan.meta.EntityManagement - Cannot generate matcher for method `NonUniqueIndex.toArray`: Method's return type Arr[R] is not a Rep
17:44:44.987 [run-main-2] WARN  scalan.meta.EntityManagement - Cannot generate matcher for method `Table.OrderBy`: Method's return type Arr[R] is not a Rep
17:44:44.988 [run-main-2] WARN  scalan.meta.EntityManagement - Cannot generate matcher for method `Table.toArray`: Method's return type Arr[R] is not a Rep
17:44:44.988 [run-main-2] WARN  scalan.meta.EntityManagement - Cannot generate matcher for method `TableCompanion.defaultOf`: Method's return type Default[Rep[Tabl

**Comment by alexeyr** [comment]
Please raise a new issue for the InterruptedException if it isn't fixed, include stack trace.
