### ISSUE TITLE
UDT symbol is not expanded if Invoke is not enabled before building graph

### ISSUE THREAD

**Issue by knizhnik** [scalan/scalan-ce#36]
In my branch I have added invocation of 
   addInvokeTester((_,_) => true)
to the prologue of  buildGraph method.
After merge if was removed by Alexey because it is caused problems in Scalan-enterprise.But without it graph is not properly extended and UDT nodes are left in the graph.
To reproduce run any single SQL test, for example test24simpleSelectTest
I didn't try to reproduce it with non-SQL tests using UDTs.

**Comment by alexeyr** [comment]
What backend are you using and what types aren't getting expanded?

**Comment by knizhnik** [comment]
LmsBackend
I will try to reproduce the problem this evening (now I can not do it).
But I have string feeling that it can be easily reproduced not with SQL tests.
Just run any  test involving UDT (MultiMap for example). But run it alone.

**Comment by alexeyr** [comment]
Ok, I'll try to reproduce it tomorrow. But it should expand everything: https://github.com/scalan/scalan-ce/blob/master/lms-backend/src/main/scala/scalan/compilation/lms/scalac/LmsCompilerScala.scala#L26

**Comment by knizhnik** [comment]
> lms-backend/it:testOnly *MvmItTests -- -z ddmvm0
[info] LmsMvmItTests:
[info] - ddmvm0 *** FAILED ***
[info]   java.lang.RuntimeException: ScalanLMSBridge: Don't know how to mirror symbol s7:PArrayCompanionAbs = PArray
[info]   at scala.sys.package$.error(package.scala:27)
[info]   at scalan.Base$class.$bang$bang$bang(Base.scala:35)
[info]   at scalan.it.lms.LmsLinAlgItTests$ProgExp.$bang$bang$bang(LmsLinAlgItTests.scala:10)
[info]   at scalan.compilation.lms.LmsBridge$$anonfun$defTransformer$1.applyOrElse(LmsBridge.scala:20)
[info]   at scalan.compilation.lms.LmsBridge$$anonfun$defTransformer$1.applyOrElse(LmsBridge.scala:19)
[info]   at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
[info]   at scalan.compilation.lms.CoreBridge$$anonfun$1.applyOrElse(CoreBridge.scala:20)
[info]   at scalan.compilation.lms.CoreBridge$$anonfun$1.applyOrElse(CoreBridge.scala:20)
[info]   at scala.PartialFunction$OrElse.apply(PartialFunction.scala:162)
[info]   at scalan.compilation.lms.CommunityBridge$$anonfun$1.applyOrElse(CommunityBridge.scala:17)
[info]   ...
[info] ScalaTest
[info] Run completed in 2 seconds, 105 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error] 	scalan.it.lms.LmsMvmItTests
[error] (lms-backend/it:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 3 s, completed Feb 9, 2015 11:28:56 AM

**Comment by alexeyr** [comment]
Please try https://github.com/scalan/scalan-ce/tree/companions-in-lms-bridge branch.
