### ISSUE TITLE
Test test23unionMultiMaps is failed

### ISSUE THREAD

**Issue by knizhnik** [scalan/scalan-ce#37]
Trying to run only this test in the latest snapshot of scalan-ce I got the following exception:

  An exception or error caused a run to abort: scala.tools.nsc.Global.LiftedAssign()Lscala/reflect/internal/Trees$LiftedAssign$; 
  java.lang.NoSuchMethodError: scala.tools.nsc.Global.LiftedAssign()Lscala/reflect/internal/Trees$LiftedAssign$;

**Comment by alexeyr** [comment]
Looks like incompatible scala-reflect or scala-compiler versions somewhere. Try using `sbt clean` first.

**Comment by alexeyr** [comment]
Works for me:

    > lms-backend/it:testOnly *SmokeItTests -- -z test23unionMultiMaps
    [info] Compiling 2 Scala sources to /home/aromanov/IdeaProjects/scalan-lite/common/target/scala-2.10/test-classes...
    [info] Compiling 19 Scala sources to /home/aromanov/IdeaProjects/scalan-lite/core/target/scala-2.10/test-classes...
    [info] Compiling 6 Scala sources to /home/aromanov/IdeaProjects/scalan-lite/community-edition/target/scala-2.10/test-classes...
    [info] Compiling 3 Scala sources to /home/aromanov/IdeaProjects/scalan-lite/lms-backend/target/scala-2.10/test-classes...
    [info] LmsSmokeItTests:
    error: write to non-mutable Sym(2) -> Some(TP(Sym(2),FieldApply(Sym(1),_1)))
    at Sym(6)=Reflect(ArrayBuilderAppend(Sym(2),Sym(5)),Summary(false,false,false,false,false,false,List(),List(),List(Sym(2)),List(Sym(2))),List())
    ... other LMS errors
    [info] - test23unionMultiMaps
    [info] ScalaTest
    [info] Run completed in 14 seconds, 130 milliseconds.
    [info] Total number of tests run: 1
    [info] Suites: completed 1, aborted 0
    [info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
    [info] All tests passed.
    [info] Passed: Total 1, Failed 0, Errors 0, Passed 1

We can try to reproduce it when you come in tomorrow.

**Comment by knizhnik** [comment]
Sorry, It was my problem - it is necessary now to move scala-lang.virtualized.* above core and community-edition projects in dependencies. Before it was enough just to place them before scala-lang.* libraries.
