### ISSUE TITLE
Problems with meta

### ISSUE THREAD

**Issue by knizhnik** [scalan/scalan-ce#48]
Adding the following class to DSL:

  implicit class StringFormatter(str: Rep[String]) {
    def toDate: Rep[Int] = (str.substring(0, 4) + str.substring(5, 7) + str.substring(8, 10)).toInt
    def toChar: Rep[Char] = str(0)
  }

cause NoSuchElementException in:

    val firstAncestorType = entity.ancestors.head

entity.ancestors is Nil

**Comment by aslesarenko** [comment]
What does it mean "Adding  to DSL"?
If you need some declarations which are not entities, it is possible to  declare them in xxxDsl, xxxDslSeq or xxxDslExp traits.

**Comment by knizhnik** [comment]
Adding to top level trait of DSL:

trait Sql extends Base { sql: SqlDsl =>
    ...
    trait Table[R] extends Reifiable[Table[R]] {
        ...   
    }
    implicit class StringFormatter(str: Rep[String]) {
      def toDate: Rep[Int] = (str.substring(0, 4) + str.substring(5, 7) + str.substring(8, 10)).toInt
      def toChar: Rep[Char] = str(0)
    }
    ...
}

**Comment by aslesarenko** [comment]
It is not supported and in fact not necessary. The content of this trait is quite restricted.
