### ISSUE TITLE
Always invoke field getters 

### ISSUE THREAD

**Issue by alexeyr** [scalan/scalan-ce#52]
In initial graph we often end up with something like `DenseVector(ExpDenseVector(xs).items)` (worse when there are multiple arguments. This can be simplified by ensuring `ExpDenseVector(xs).items` is `xs`. Options: 

1. Generate rewrite rules in codegen like `DenseVectorMethods.items(Def(x: ExpDenseVector[_])) => x.items`.
2. Mark field getters with an annotation (`@AlwaysInvoke` or `@Field`?). The benefit is that this can be unified with `*Companion.apply` methods which are always invoked already and needs less generated code.
3. Always invoke any `val` (probably not what we want).

/cc @aslesarenko

**Comment by aslesarenko** [comment]
+1 for @Field annotation. 
First version will slowdown rewriting.

**Comment by alexeyr** [comment]
Potential problem with annotation is that we need to check if the method shows up as `ExpDenseVector.items()` (then we can annotate it, since it's defined in generated code) or `DenseVector.items()`. 

A better 3 option is to use Scala reflection to check if a method is a constructor param.

**Comment by aslesarenko** [comment]
Agree,  Scala reflection is possible solution, but this policy may also apply to other methods which are not constructor params.

**Comment by alexeyr** [comment]
As suspected, the method is `DenseVector.items()`, so it can't be annotated.

**Comment by aslesarenko** [comment]
It will be possible in future to inherit MyDenseVector from DenseVector, and this new descendant can be in different package. 
In this case what will be the effect of annotations attached to DenseVector, should they propagate along the hierarchy?

**Comment by alexeyr** [comment]
Well, it doesn't happen by default, but something can be done using (Java or Scala) reflection (we already have a similar problem with `OverloadId`).
