### ISSUE TITLE
Simplify `ReifiableExp`

### ISSUE THREAD

**Issue by alexeyr** [scalan/scalan-ce#53]
Now that we support abstract elements, it's probably possible to only have a single type parameter to `ReifiableExp` (the concrete type). This will let us finally avoid the Scala 2.11 bug and simplify code somewhat.

**Comment by aslesarenko** [comment]
+1 if we can avoid things like this 
`element[SVertex[V, E]].asInstanceOf[Elem[Vertex[V,E]]]`
